"""
Popularlist Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

import flet as ft
from fletx.core import (
    RxStr, RxList
)
from fletx.decorators import (
    simple_reactive, reactive_list
)

from app.models import Article, ArticleSource
from .newscard_component import NewscardComponent

@reactive_list(
    items_attr = 'rx_items',
    item_builder = lambda item, index: NewscardComponent(data = item),
    empty_builder = lambda: ft.Container(
        height = 100,
        width = 100,
        bgcolor = 'green'
    ),
    animate_changes = True
)
class PopularlistComponent(ft.ListView):    # 🧩 You can replace ft.Container with any other Flet control
    """Reactive Popularlist Widget"""

    def __init__(self, rx_items: RxList = RxList([]), **kwargs):
        self.rx_items: RxList = rx_items #

        super().__init__(
            expand = True,
            spacing = 20,
            horizontal = True,
            **kwargs
        )

    def did_mount(self):
        """Actions after mount."""
        self._is_mounted = True

    def before_update(self):
        """Action to perform before component update"""

        # self._rebuild_list()
        print("\n\nupdating................................................\n\n")
        # print(self.rx_items.value, self._is_mounted)

        self.controls = [
            NewscardComponent(data = item) for item in self.rx_items
        ]


# items = RxList([
#     Article(
#         source = ArticleSource(
#             id = 'bbc',
#             name = 'bbc news'
#         ),
#         author = 'John doe',
#         title = "We're building news app with flet and FletX",
#         description = 'A FletX showcase creating a sample News App',
#         url = 'https://alldotpy.github.io/FletX/',
#         url_to_image = 'https://alldotpy.github.io/FletX/assets/logo/fletx_t.png',
#         published_at = '',
#         content = (
#             'we made a sample news app using the GetX-like micro-framework for flet. '
#             'This project shows how to use flet with fletx create reactive apps, '
#             'it shows also how to usee some fletx compnents like Controllers, Pages, '
#             'Services, Reactive States with RX[T] variants, widget decorators and more...'
#         )
#     )
# ])

# mylist = PopularlistComponent(
#     rx_items = items
# )

# mylist._setup_list_binding()
# mylist._rebuild_list()
# mylist.did_mount()
# # mylist._list_observer.notify()
# print(mylist._is_mounted)
# print(mylist.rx_items)
# print(mylist.controls)
# print(mylist._list_observer)
# print(mylist._get_control_name())

# items.value =  [
#     Article(
#         source = ArticleSource(
#             id = 'bbc',
#             name = 'bbc news'
#         ),
#         author = 'John doe',
#         title = "We're building news app with flet and FletX",
#         description = 'A FletX showcase creating a sample News App',
#         url = 'https://alldotpy.github.io/FletX/',
#         url_to_image = 'https://alldotpy.github.io/FletX/assets/logo/fletx_t.png',
#         published_at = '',
#         content = (
#             'we made a sample news app using the GetX-like micro-framework for flet. '
#             'This project shows how to use flet with fletx create reactive apps, '
#             'it shows also how to usee some fletx compnents like Controllers, Pages, '
#             'Services, Reactive States with RX[T] variants, widget decorators and more...'
#         )
#     ),
#     Article(
#         source = ArticleSource(
#             id = 'bbc',
#             name = 'bbc news'
#         ),
#         author = 'John doe',
#         title = "We're building news app with flet and FletX",
#         description = 'A FletX showcase creating a sample News App',
#         url = 'https://alldotpy.github.io/FletX/',
#         url_to_image = 'https://alldotpy.github.io/FletX/assets/logo/fletx_t.png',
#         published_at = '',
#         content = (
#             'we made a sample news app using the GetX-like micro-framework for flet. '
#             'This project shows how to use flet with fletx create reactive apps, '
#             'it shows also how to usee some fletx compnents like Controllers, Pages, '
#             'Services, Reactive States with RX[T] variants, widget decorators and more...'
#         )
#     ),
#     Article(
#         source = ArticleSource(
#             id = 'bbc',
#             name = 'bbc news'
#         ),
#         author = 'John doe',
#         title = "We're building news app with flet and FletX",
#         description = 'A FletX showcase creating a sample News App',
#         url = 'https://alldotpy.github.io/FletX/',
#         url_to_image = 'https://alldotpy.github.io/FletX/assets/logo/fletx_t.png',
#         published_at = '',
#         content = (
#             'we made a sample news app using the GetX-like micro-framework for flet. '
#             'This project shows how to use flet with fletx create reactive apps, '
#             'it shows also how to usee some fletx compnents like Controllers, Pages, '
#             'Services, Reactive States with RX[T] variants, widget decorators and more...'
#         )
#     )
# ]
