"""
Popularlist Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

import flet as ft
from fletx.core import (
    RxStr, RxList
)
from fletx.decorators import (
    simple_reactive, reactive_list
)

from app.models import Article, ArticleSource
from .newscard_component import NewscardComponent

@reactive_list(
    items_attr = 'rx_items',
    item_builder = lambda item, index: NewscardComponent(data = item),
    empty_builder = lambda: ft.Container(
        height = 100,
        width = 100,
        bgcolor = 'green'
    ),
    animate_changes = True
)
class PopularlistComponent(ft.ListView):
    """Reactive Popularlist Widget"""

    def __init__(self, rx_items: RxList = RxList([]), **kwargs):
        self.rx_items: RxList = rx_items #

        super().__init__(
            expand = True,
            spacing = 20,
            horizontal = True,
            **kwargs
        )

    def did_mount(self):
        """Actions after mount."""
        self._is_mounted = True

    def before_update(self):
        """Action to perform before component update"""

        # I think @reactive_list decoratore have some issues 
        # when rebuilding liste elements, so i'll do it manually
        # fot this sample project. It will be updated once the 
        # issues are fixed.
        self.controls = [
            NewscardComponent(data = item) for item in self.rx_items
        ]
